# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

- id: doi:10.1016/j.canlet.2024.217112
  type: paper
  image: images/publication/PI3KPROTAC.jpg

- id: doi:10.1016/j.bmc.2024.117967
  type: paper
  image: images/publication/TheapplicationofPROTACs.jpg

- id: doi:10.1021/jacs.4c11930
  type: paper
  image: images/publication/ADualTargetandDualMechanism.jpeg

- id: doi:10.1038/s41421-024-00711-x
  type: paper
  image: images/publication/PROTACforBruton.jpg

- id: doi:10.1038/s41589-024-01683-5
  type: paper
  image: images/publication/TargetingSmurf1.jpg

- id: doi:10.1016/j.cclet.2024.109577
  type: paper
  image: images/publication/DevelopingselectivePI3K.jpg

- id: doi:10.1016/j.biopha.2024.116972
  type: paper
  image: images/publication/CDK9targetingPROTAC.jpg

- id: doi:10.1016/j.scib.2024.03.056
  type: paper
  image: images/publication/Targetingtheundruggables.jpg

- id: doi:10.1002/advs.202308186
  type: paper
  image: images/publication/DegradationBasedProteinProfiling.jpg

- id: doi:10.1016/j.cclet.2022.107924
  type: paper
  image: images/publication/DevelopingpotentBTKC481S.jpg

- id: doi:10.15212/AMM-2023-0039
  type: paper
  image: images/publication/PROTACstargetingepogenetic.jpg

- id: doi:10.1007/s11684-023-1027-5
  type: paper
  image: images/publication/Discoveryofdegradercellcycle.jpg

- id: doi:10.1038/s41421-023-00544-0
  type: paper
  image: images/publication/BRD4targetingPROTAC.jpg

- id: doi:10.1039/d3md00216k
  type: paper
  image: images/publication/DesignsynthesisandevaluationofBTK.jpg

- id: doi:10.1039/d2cs00220e
  type: paper
  image: images/publication/Chemistriesofbifunctional.jpg

- id: doi:10.1038/s41392-022-00999-9
  type: paper
  image: images/publication/PROTACsgreatopportunitesforacademia.jpg

- id: doi:10.1158/2326-6066.CIR-21-0806
  type: paper
  image: images/publication/CDK2InhibitionEnhances.jpg

- id: doi:10.1038/s41392-022-00970-8
  type: paper
  image: images/publication/PROTACmediatedFKBP12.jpg

- id: doi:10.1038/s41422-021-00533-6
  type: paper
  image: images/publication/MergingPROTACandmolecularglue.jpg

- id: doi:10.3389/fcell.2021.685106
  type: paper
  image: images/publication/OpportunitiesandChallenges.jpg

- id: doi:10.1038/s41589-021-00742-5
  type: paper
  image: images/publication/DiscoveryofCDK2AML.jpg

- id: 10.1016/j.isci.2021.103177
  type: paper
  image: images/publication/RapamycinrecruitsSIRT2.jpg

- id: 10.1021/acs.jmedchem.0c00967
  type: paper
  image: images/publication/GlobalPROTACToolbox.jpg

- id: 10.1007/s13238-020-00732-8
  type: paper
  image: images/publication/FAKtargetingPROTAC.jpg

- id: 10.1021/acs.jmedchem.0c00339
  type: paper
  image: images/publication/DegradationversusInhibition.jpg

- id: doi:10.1021/acsmedchemlett.9b00597
  type: paper
  image: images/publication/PROTACTechnonlogyOpportunities.jpg

- id: doi:10.1039/C9CC08509B
  type: paper
  image: images/publication/PlasticityHDAC6.jpg

- id: doi:10.1021/acs.biochem.9b00848
  type: paper
  image: images/publication/PROTACsasPotential.jpeg