# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

- id: doi:10.1016/j.canlet.2024.217112
  type: paper
  image: images/publication/PI3KPROTAC.jpg

- id: doi:10.1016/j.bmc.2024.117967
  type: paper
  image: images/publication/TheapplicationofPROTACs.jpg

- id: doi:10.1021/jacs.4c11930
  type: paper
  image: images/publication/ADualTargetandDualMechanism.jpeg

- id: doi:10.1038/s41421-024-00711-x
  type: paper
  image: images/publication/PROTACforBruton.jpg

- id: doi:10.1038/s41589-024-01683-5
  type: paper
  image: images/publication/TargetingSmurf1.jpg